insert into Brands (Name, Description, Status) values ('Alastair', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 1);
insert into Brands (Name, Description, Status) values ('Major', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 1);
insert into Brands (Name, Description, Status) values ('La verne', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1);
insert into Brands (Name, Description, Status) values ('Julina', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 1);
insert into Brands (Name, Description, Status) values ('Frank', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0);
/*##################################################################################*/
insert into Categories (Name, Description, Status) values ('Sheila-kathryn', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into Categories (Name, Description, Status) values ('Caryl', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 0);
insert into Categories (Name, Description, Status) values ('Alvira', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 1);
insert into Categories (Name, Description, Status) values ('Moss', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 0);
insert into Categories (Name, Description, Status) values ('Bondie', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
/*##################################################################################*/
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 16', 'Morbi vel lectus in quam fringilla rhoncus.', '1.png', 56633.0, 978, 3.7, 1, 43.41, 3, 4);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 11', 'Suspendisse potenti.', '1.png', 111761.81, 369, 4.9, 1, 12.1, 2, 5);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 16', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '3.png', 4537.93, 295, 0.7, 1, 60.33, 2, 1);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 13', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '3.png', 38304.28, 701, 2.9, 1, 45.3, 2, 5);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 16', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '4.png', 13811.15, 804, 1.9, 0, 2.0, 4, 1);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 14', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '5.png', 142815.63, 992, 1.6, 1, 35.25, 3, 1);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 13', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '1.png', 178287.05, 28, 0.0, 1, 91.6, 2, 2);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 15', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '1.png', 111900.07, 834, 3.9, 1, 66.2, 4, 4);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 12', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2.png', 80638.7, 971, 4.9, 1, 47.42, 3, 3);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 11', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', '3.png', 128447.52, 797, 3.5, 1, 6.23, 2, 1);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 13', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '1.png', 130921.79, 262, 1.8, 1, 89.98, 1, 1);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 16', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2.png', 35910.32, 172, 0.2, 1, 95.74, 1, 5);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 12', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', '2.png', 106480.64, 364, 4.2, 1, 95.31, 4, 4);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 13', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '2.png', 61732.26, 240, 1.6, 1, 51.43, 2, 4);
insert into Products (Name, Description, MainImg, Price, Quantity, Rate, Status, Discount, CategoryId, BrandId) values ('Iphone 11', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '1.png', 98299.04, 728, 1.4, 1, 88.18, 5, 2);
GO

UPDATE Products
SET BrandId = 1
UPDATE Products
SET CategoryId = 1
GO